### ISSUE TITLE
Upgrading to scala 3.3.0-RC6 breaks Zio environment (can't find `Quill::Sqlite[=SnakeCase]`)

### ISSUE THREAD

**Issue by bishabosha** [softwaremill/realworld-tapir-zio#107]
Here is my [working branch](https://github.com/bishabosha/realworld-tapir-zio/tree/prepare-3.3.x), which I have removed unused imports on.

On that branch, `sbt run` works with the current scala version (3.2.1).

However, as soon as I change `scalaVersion` to 3.3.0-RC6, then the runtime breaks, with this error:
```scala
13:58:24.045 [ZScheduler-Worker-4] DEBUG com.softwaremill.realworld.Main -- timestamp=2023-05-19T13:58:24.045344+02:00 level=DEBUG thread=zio-fiber-8 message="Fiber zio-fiber-8 did not handle an error" cause=
java.lang.Error: Defect in zio.ZEnvironment: Could not find Quill::Sqlite[=SnakeCase] inside ZEnvironment(Quill::Sqlite[+SnakeCase] -> io.getquill.jdbczio.Quill$Sqlite@3bc36c29)
	at zio.ZEnvironment$$anon$1.get(ZEnvironment.scala:167)
	at zio.ZIO$ServiceWithZIOPartiallyApplied$.apply$extension$$anonfun$13$$anonfun$1(ZIO.scala:5306)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
	at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:476)
```

**Comment by bishabosha** [comment]
seems like the environment contains a slightly different Tag? `Quill::Sqlite[+SnakeCase]` rather than `Quill::Sqlite[=SnakeCase]`

**Comment by bishabosha** [comment]
locally it seems adding an explicit dependency to `dev.zio:zio_3:2.0.13` fixes it

**Comment by wydra98** [comment]
Thank you for your comment, we will do a revisit and code review when the issue at https://github.com/zio/izumi-reflect/issues/391 will be resolved.
